# Generated by Django 4.0.3 on 2022-04-16 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_dentist_dentistname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dentist',
            name='dentistEmail',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
