# Generated by Django 4.0.3 on 2022-04-16 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_dentist_dentistemail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dentist',
            name='dentistEmail',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='dentist',
            name='dentistName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
